### PR TITLE
changes for kernel v6.9

### PR DESCRIPTION
**Pull request by 5kft**
Hi @morrownr , a simple change is needed for this driver to work in kernel v6.9.  Hope this is helpful!

### CODE REVIEW

**Comment by morrownr** [comment]
Looks like there was a decision that the old code worked better.

Thanks.

**Comment by 5kft** [comment]
Yes, the difference in performance is an order of magnitude - definitely worth keeping this driver alive for the time being.

**Comment by morrownr** [comment]
This driver needs to kept alive until any replacement, such as rtw88, is as good or better. Now that rtw88 is working, we can work on other things we could not really test before. Performance, as you noted, sucks in rtw88. AP mode is basically dead in the water. If we can get the performance up and see good stable performance out of managed, AP, monitor and P2P modes before the next LTS kernel at the end of the year, that would be great.

**Comment by morrownr** [comment]
@5kft 

I have been feeling less than optimal for the last 2 days so am on a reduced schedule but I happened to remember the kernel 6.10 is in the wild. Have you looked to see if anything is needed?

I think we have more code draps for the 8821/11au soon. I am hoping that we discover more things while working on that driver that can help with this driver. I'm known for a long time that the 8821/11cu chip is just more problematic but maybe we can keep making progress as we go.

**Comment by 5kft** [comment]
>  I happened to remember the kernel 6.10 is in the wild. Have you looked to see if anything is needed?

Yes, I looked into this - no changes are needed (at least for the 8821au and 8821cu) - the drivers work fine (I tested against 6.10.0-rc2).

> I think we have more code draps for the 8821/11au soon. I am hoping that we discover more things while working on that driver that can help with this driver. I'm known for a long time that the 8821/11cu chip is just more problematic but maybe we can keep making progress as we go.

Indeed - I have a number of 8821cu adapters that are actually better than my 8821aus, so it'd be wonderful to see a bit more progress in the rtw88 work for the 8821cu...  The only two things I see are 1) RX aggregation support and 2) LED support.  I was thinking I might take a look into the deltas for (1) and compare to dubhater's changes in the rtw88 8821au driver and see if how difficult this might be...

The last time I tried the rtw88 8821au driver it works great in all cases for me.  Would love to see the 8821cu reach the same level.

**Comment by morrownr** [comment]
> The last time I tried the rtw88 8821au driver it works great in all cases for me. Would love to see the 8821cu reach the same level.

Same thoughts here. I think dubhater is currently working on some minor details with 8821/11au... such as something to do with power saving. He is also working ahead with 8812au. My best guess is that if his next drop works well, we can look at upstreaming the 8821/11au.

What you could do first is find the code that runs the led in 8821/11au and see if it will work on 8821/11cu. If it does work, I have the ability to directly add it to the repo... I would, of course, test it first. I use `meld` to look for deltas. What do you use?

Of course, the RX agregation code would be nice also and I'm sure dubhater would appreciate the help as I think he is being encouraged to work the 8812au code hard as it is so heavily used by Linux users. We could split the 2 projects but I am not feeling well so it might take me awhile to get going.

Let me know.

**Comment by morrownr** [comment]
FYI:

$ grep -r "LED" * | grep "8821a"
rtw8821a.c:	rtw_write32_mask(rtwdev, REG_LED_CFG, BIT_DPDT_SEL_EN, 0);
rtw8821a.c:	rtw_write32_mask(rtwdev, REG_LED_CFG, BIT_DPDT_WL_SEL, 1);
rtw8821a.c:		rtw_write8(rtwdev, REG_LED_CFG + 2, BIT(1) | BIT(5));
rtw8821a.c:		rtw_write8(rtwdev, REG_LED_CFG, BIT(1) | BIT(5));

Couldn't keep myself from taking a look. Do you want to work the RX aggregation and I'll take the LED?

**Pull request merged**
