### PR TITLE
fix: os_dep/osdep_service.c: Add a checking kernel version (>=5.4) fo…

### PR DESCRIPTION
**Pull request by how2flow**
…r MODULE_IMPORT_NS

[error 1] in Rockchip v20230524 kernel 5.10.y

ERROR: modpost: module 8821cu uses symbol kernel_write from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.
ERROR: modpost: module 8821cu uses symbol kernel_read from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.
ERROR: modpost: module 8821cu uses symbol filp_open from namespace VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.
make[1]: *** [scripts/Makefile.modpost:168: modules-only.symvers] Error 1
make[1]: *** Deleting file 'modules-only.symvers'
make: *** [Makefile:1524: modules] Error 2
make: *** Waiting for unfinished jobs....

[error 2] build error in kernel 4.19.y

type defaults to 'int' in declaration of 'MODULE_IMPORT_NS' [-Werror=implicit-int] ...

### CODE REVIEW

**Comment by how2flow** [comment]
@alkisg 

Still getting errors regarding kernel version?

**Comment by alkisg** [comment]
In that specific Buster VM with kernel 4.19, without testing yet, I'm pretty sure the problem won't happen anymore since we check for kernel >= 5.4.

But I added that check based on a random google hit. This isn't appropriate; it's best that we find the source for the VFS_internal... definition and that we verify it was actually introduced in kernel 5.4.

While just blindly testing in a couple of VMs that we happen to have around, has the risk of breaking things for many users...

**Comment by how2flow** [comment]
Also, unlike the mainline kernel, I found that there is a specific keyword definition separately.

**Comment by how2flow** [comment]
I've conducted the test and there's no problem anymore.
Please feel free to contact me if there is a problem.

**Comment by morrownr** [comment]
Thanks for the short background. Now things are making more sense.

I've got some health issues I am dealing with but I'll get this in soon.

**Comment by how2flow** [comment]
I hope you get well ..!

**Comment by alkisg** [comment]
This problem still exists for 8812au, 88x2bu, 8821cu and 8852bu in OrangePi5 Bullseye with kernel 5.10.110-rockchip-rk3588.

Replacing the `#ifdef ANDROID...` with the [kernel 5.4 version check](https://github.com/morrownr/8821cu-20210916/pull/101#issuecomment-1662858828) solves the issue. I think we should switch to that other check...

**Comment by morrownr** [comment]
@alkisg 

> Replacing the #ifdef ANDROID... with the kernel 5.4 version check solves the issue. I think we should switch to that other check...

I got lost when trying to sort out what you were saying we should do. I remember this issue but I'm not 100% right now. Can you be more specific about what we need to do? If we can get it working here then I will try to take the fix over to the other repos.

@morrownr

**Comment by alkisg** [comment]
Heya Nick, I mean that we should do these:

- To change the check from `#ifdef ANDROID` to `if kernel > 5.4`
- To move that code to os_intfs.c, where the other MODULE_xxx are declared

Similar online code [there](https://github.com/Freescale/kernel-module-imx-gpu-viv/blob/master/kernel-module-imx-gpu-viv-src/hal/os/linux/kernel/gc_hal_kernel_driver.c#L72C1-L74C7).
The .diff follows:

```diff
diff --git a/os_dep/linux/os_intfs.c b/os_dep/linux/os_intfs.c
index 2c07635..f5f32dc 100644
--- a/os_dep/linux/os_intfs.c
+++ b/os_dep/linux/os_intfs.c
@@ -21,6 +21,15 @@ MODULE_LICENSE("GPL");
 MODULE_DESCRIPTION("Realtek Wireless Lan Driver");
 MODULE_AUTHOR("Realtek Semiconductor Corp.");
 MODULE_VERSION(DRIVERVERSION);
+/* Include namespace when file system namespace errors occur during kernel build.
+ * about 'kernel_read' or 'kernel_write'
+ *
+ * This declaration was created to resolve an error on the Rockchip side
+ * You can modify or add flags in the fs/Makefile.
+ */
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 4, 0)
+MODULE_IMPORT_NS(VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver);
+#endif
 
 /* module param defaults */
 int rtw_chip_version = 0x00;
diff --git a/os_dep/osdep_service.c b/os_dep/osdep_service.c
index 0413f0a..5f8f8a4 100644
--- a/os_dep/osdep_service.c
+++ b/os_dep/osdep_service.c
@@ -52,16 +52,6 @@ inline int RTW_STATUS_CODE(int error_code)
 }
 #endif
 
-/* Include namespace when file system namespace errors occur during kernel build.
- * about 'kernel_read' or 'kernel_write'
- *
- * This declaration was created to resolve an error on the Rockchip side
- * You can modify or add flags in the fs/Makefile.
- */
-#ifdef ANDROID_GKI_VFS_EXPORT_ONLY
-       MODULE_IMPORT_NS(VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver);
-#endif
-
```

**Comment by how2flow** [comment]
> This problem still exists for 8812au, 88x2bu, 8821cu and 8852bu in OrangePi5 Bullseye with kernel 5.10.110-rockchip-rk3588.
> 
> Replacing the `#ifdef ANDROID...` with the [kernel 5.4 version check](https://github.com/morrownr/8821cu-20210916/pull/101#issuecomment-1662858828) solves the issue. I think we should switch to that other check...

How does the error log come out?

**Comment by alkisg** [comment]
Example output when the patch is NOT applied:

> Loading new rtl8821cu-5.12.0 DKMS files...
> Building for 5.10.110-rockchip-rk3588
> Building initial module for 5.10.110-rockchip-rk3588
> Error! Bad return status for module build on kernel: 5.10.110-rockchip-rk3588 (aarch64)
> Consult /var/lib/dkms/rtl8821cu/5.12.0/build/make.log for more information.

Also, attaching [make.log](https://github.com/morrownr/8821cu-20210916/files/12615541/make-log.txt).

**Pull request closed without merging**
